# Copyright (c) 2024 The ZMK Contributors
# SPDX-License-Identifier: MIT

# Disable USB logging to allow HID keyboard to work
# CONFIG_ZMK_USB_LOGGING=y

# Uncomment the following lines to enable deep sleep
# CONFIG_ZMK_SLEEP=y
# CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Uncomment to increase BLE transmit power
# CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

CONFIG_ZMK_KEYBOARD_NAME="SWEEP-v3"
CONFIG_ZMK_USB=y
